kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}-bc
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.buildconfig.git.uri }}
      ref: {{ .Values.buildconfig.git.ref | default "main" }}
    contextDir: {{ .Values.buildconfig.git.contextDir }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.buildconfig.dockerfilePath | default "Containerfile"  }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}-is:{{ .Values.imagestream.tag | default "latest" }}

