apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.imagestream.name }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: {{ .Values.imagestream.tag | default "latest" }}
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.sourceImage }}
    referencePolicy:
      type: Source
